name: Deploy Job Step
on:
  workflow_call:
    inputs:
      artifact_name:
        description: Artifact folder name
        required: true
        default: dist
        type: string
      yarn_cache_dir:
        description: Yarn cache directory
        required: true
        default: node-modules-
        type: string
    outputs:
      result:
        description: The result of the job
        value: ${{jobs.deploy.outputs.dist-result}} ${{jobs.deploy.outputs.node-cache}}
jobs:
  deploy:
    outputs:
      dist-result: ${{steps.set_result_output.outputs.step-result}}
      node-cache: ${{steps.get_cache_dependencies.outputs.cache-hit}}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
      - name: Get Cache Dependencies
        id: get_cache_dependencies
        uses: actions/cache@v2
        with:
          # Bring yarn_cahe_dir from the input
          path: ${{inputs.yarn_cache_dir}}
          key: node-modules-${{hashFiles('**/yarn.lock')}}
      - name: Get Dist Artifact
        id: get_dist_artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.artifact_name}}
      - name: List Files
        run: pwd && ls -la && ls .github/workflows
      - name: Install Dependencies
        if: steps.get_cache_dependencies.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Run Dist
        run: yarn start:prod
      - name: Set Result Output
        id: set_result_output
        run: echo "step-result=success" >> $GITHUB_OUTPUT
      - name: Checking Actual Job
        run: echo "${{toJson(job)}}"
      - name: Dummy Step
        run: echo "This is a dummy step"
